#!/bin/bash

#
# multiseek_mod: Same as multiseek, but saves all the .prd files
#

seek=$1
nthread=$2
outfile=$3
filfile=$4
tlength=$5
options="$6"
output_cmd=""

date=`date +%s`

A=''
i=0
\rm -f seeklist.*
\rm -f $filfile.????.??.prd
\rm -f $outfile.prd
for file in `ls $filfile.????.??.tim`; do
	if [[ $i -ge $nthread ]] ; then
		i=0
	fi

	rm -f $file.prd
	touch seeklist.$i
	#echo "$seek $file -q -fftw -t$tlength > /dev/null" >> seeklist.$i

	if [[ "$seek" =~ "pch-seek" ]] ; then
		seekfname=`basename $file .tim`
		output_cmd="--write-prd $seekfname.prd"
		makePsrXml $file > $file.xml
		file=$file.xml
	fi

	echo "$seek $file $output_cmd -t$tlength $options $A> /dev/null" >> seeklist.$i
	A='-A'
	i=`expr $i + 1`

done

for ((i=0;i<$nthread;i+=1)); do
	echo "starting $i"
	bash seeklist.$i &
	procs[$i]=$!
done

for ((i=0;i<$nthread;i+=1)); do
	wait ${procs[$i]}
	echo "done $i"
done

rm $outfile.prd
echo "Making final prd file: $outfile.prd"

cat $filfile.????.??.prd > $outfile.prd
\rm -r $filfile.????.??.prd
\rm -r $filfile.????.??.tim.xml

echo "done"
