#!/bin/tcsh

if ( $# < 1 ) then
	echo "takes a fil file name"
	exit 1
endif

set filename = $1

if ( -e $filename == 0 ) then
	echo "selected file '$filename' does not exist"
endif

set dedisperse_all = $HITRUN/bin/dedisperse_all
set zaptime = $HITRUN/bin/giant
set filedit = $HITRUN/bin/filedit

echo "Making DM=0 timeseries"
set cmd="${dedisperse_all} ${filename} -d 0 0 -g 1000000"
echo $cmd
$cmd

set dmzero = ${filename}.0000.00.tim

echo "Mowing lawn to find bad time samples"
$zaptime $dmzero -z

set mean = `head -n 1 tchan.kill | awk '{print $1}' | awk -F "#" '{print (($2+128)*16/1024)}'`
set stdev = `head -n 1 tchan.kill | awk '{print ($2/2)}'`

echo "Zapping the bad time samples in the fil file"
cp ${filename} ${filename}.orig
$filedit ${filename} -m $mean -s $stdev -k tchan.kill
echo "And we're done!"
